### ISSUE TITLE
[PS4] TGA font not work.

### ISSUE THREAD

**Issue by zerlkung** [Kaplas80/SakunaTools#2]
in ps4 use .gnf format can you make support on ps4 like --switch sir.

**Comment by Kaplas80** [comment]
I can try when I have some time. Can you send me a .gnf example file?

**Comment by zerlkung** [comment]
> I can try when I have some time. Can you send me a .gnf example file?

Is there sir.

https://www.mediafire.com/file/gjyl0v9dq4buun2/Sample.rar/file

thank you.
