### ISSUE TITLE
Wrong .arc output with Sakuna Switch

### ISSUE THREAD

**Issue by cucholix** [Kaplas80/SakunaTools#3]
I'm using this tool to change the audio for a better quality one, once I place the resulting audio .arc back on Switch there's no audio. Comparing original .arc and the one generated by SakunaTools with HxD you can notice small differences, it seems that data headers are missing some info. 

Using --switch argument makes no difference.

**Comment by Kaplas80** [comment]
I don't own a switch, so I can't try it.

Could you try to extract the .arc, then repack it without change any file and run the game? If that works and there is audio, then it is not an app problem. If that fails, then I'll need you to share the original .arc file to make some tests.

**Comment by cucholix** [comment]
I included a small arc, since the voice audio arc is too big, if you still need the original audio voice arc let me know.
[arcs.zip](https://github.com/Kaplas80/SakunaTools/files/9543410/arcs.zip)

**Comment by cucholix** [comment]
Tried with the file AudioEventVoice_Jp.arc unpacked then repacked the untouched folder with your tool, using --switch command, and the resulting .arc doesn't work on Switch, there's no audio.

Here's the repacked and original .arc
https://mega.nz/file/EAYziQzD#rR5rnL1gMVhNAz-vJMFtJqNbXDd4D0FItrtiAac0TvA

**Comment by Kaplas80** [comment]
I think I've found the problem:

`AudioEventVoice_Jp.arc` is uncompressed but my app compresses it. I've added a new command line flag `--no-compress` to skip compression.

Can you try this version using that option? [1.2.1_alpha.zip](https://github.com/Kaplas80/SakunaTools/files/9549667/1.2.1_alpha.zip)

PS. You don't need the `--switch` flag. It is only used for font images.

**Comment by cucholix** [comment]
Thanks, will try when I get home, and report back.

**Comment by cucholix** [comment]
It works now, thanks
